INSERT IGNORE INTO designation(DES_ID,DESG_NAME,LEVEL) VALUES (1,'Director',1);
INSERT IGNORE INTO designation(DES_ID,DESG_NAME,LEVEL) VALUES (2,'Manager',10);
INSERT IGNORE INTO designation(DES_ID,DESG_NAME,LEVEL) VALUES (3,'Lead',20);
INSERT IGNORE INTO designation(DES_ID,DESG_NAME,LEVEL) VALUES (4,'Developer',30);
INSERT IGNORE INTO designation(DES_ID,DESG_NAME,LEVEL) VALUES (5,'DevOps',30);
INSERT IGNORE INTO designation(DES_ID,DESG_NAME,LEVEL) VALUES (6,'QA',30);
INSERT IGNORE INTO designation(DES_ID,DESG_NAME,LEVEL) VALUES (7,'Intern',40);

# INSERT IGNORE INTO Employee(EMP_NAME,PARENT_ID,DES_ID) VALUES('THOR',null,1);
# INSERT IGNORE INTO Employee(EMP_NAME,PARENT_ID,DES_ID) VALUES('IRONMAN',1,2);
# INSERT IGNORE INTO Employee(EMP_NAME,PARENT_ID,DES_ID) VALUES('HULK',1,3);
# INSERT IGNORE INTO Employee(EMP_NAME,PARENT_ID,DES_ID) VALUES('CAPTAINAMERICA',1,2);
# INSERT IGNORE INTO Employee(EMP_NAME,PARENT_ID,DES_ID) VALUES('WARMACHINE',2,6);
# INSERT IGNORE INTO Employee(EMP_NAME,PARENT_ID,DES_ID) VALUES('VISION',2,5);
# INSERT IGNORE INTO Employee(EMP_NAME,PARENT_ID,DES_ID) VALUES('SPIDERMAN',2,7);
# INSERT IGNORE INTO Employee(EMP_NAME,PARENT_ID,DES_ID) VALUES('BLACKWIDOW',3,4);
# INSERT IGNORE INTO Employee(EMP_NAME,PARENT_ID,DES_ID) VALUES('FALCON',4,4);
# INSERT IGNORE INTO Employee(EMP_NAME,PARENT_ID,DES_ID) VALUES('ANTMAN',4,3);

